language: node_js

sudo: false
dist: bionic

node_js:
  - '10'

#branches:
#  only:
#  - master

addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm i -g npm@latest
  - npm install -g @angular/cli

#install:
#  - travis_retry npm i

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start


script:
  - npm run lint:ci
  - npm run test
  #- npm run build

#git:
#  depth: 1
