language: node_js

sudo: false
dist: bionic

node_js:
  - '10'

services:
  - xvfb

#branches:
#  only:
#  - master

addons:
  chrome: stable
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - g++-4.8

before_install:
  - npm i -g npm@latest
  - npm install -g @angular/cli

#install:
#  - travis_retry npm i

script:
  - npm run lint:ci
  - npm run test
  #- npm run build

#git:
#  depth: 1
