language: node_js

sudo: false
dist: bionic

node_js:
  - '10'

#branches:
#  only:
#  - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm i -g npm@latest
  - npm install -g @angular/cli

#install:
#  - travis_retry npm i

before_script:

script:
  - npm run lint:ci
  - npm run test
  - npm run build:prod

#git:
#  depth: 1
